### ISSUE TITLE
Transform generalized SPIR-V into SPIR-V for Vulkan, to support HLSL compilation

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#687]
A natural translation of some HLSL can result in SPIR-V which does not follow Vulkan's rules.

For example, see HLSL examples in https://github.com/KhronosGroup/glslang/issues/850 
Instead of making HLSL front ends more complex, it is advantageous to transform the generalized SPIR-V generated by the front end into the restricted SPIR-V acceptable to Vulkan.

One such transform is copy propagation of image values through structs, as described in https://github.com/KhronosGroup/SPIRV-Tools/issues/679.

This issue will catalog the list of needed transforms.

Ideally we'll also derive a (crisp?) description of the generalized SPIR-V dialect that we are able to reduce to Vulkan-acceptable SPIR-V.

The list of transforms (expect this to grow!):
- [x] Copy propagation of image values through struct member assignment, including when done through store/load through memory. See https://github.com/KhronosGroup/SPIRV-Tools/issues/679
- [x] Dead-code elimination: HLSL allows invalid stuff to happen in dead code. Glslang already eliminates functions not in the entry-point's call tree due to this, but further DCE is needed to catch all cases.  Example: `if (false) SSBO = A; else SSBO = B;` must resolve statically, not dynamically, to knowing SSBO is either A or B when SSBO is a StorageBuffer buffer object.
   - [x] Eliminate unreachable blocks in a function where possible https://github.com/KhronosGroup/SPIRV-Tools/issues/702 
   - [x] Eliminate unreachable functions without an entry point https://github.com/KhronosGroup/SPIRV-Tools/issues/703
- [ ] Inline functions that have arguments or return values that are of an opaque type. https://github.com/KhronosGroup/SPIRV-Tools/issues/754

cc @johnkslang @antiagainst

**Comment by antiagainst** [comment]
It would also be nice to have some criteria dictating whether a "pass" should happen in the frontend or here in SPIRV-Tools.

For example, non-floating-point matrix types are not allowed by SPIR-V spec. Emulating them using other types (arrays maybe) in the frontend is also complicated. Should we let the front end emit non-fp matrix instructions and  have a pass here to translate them or actually it should be the task of the frontend? I feel I don't quite have a clear-cut criterion.

**Comment by johnkslang** [comment]
Put things in this list to indicate your belief that the best way to solve a specific case is a general-purpose transform living in SPIRV-tools rather than in front-end specific code.  Discussion might update beliefs and subsequently where the issue resides.

**Comment by johnkslang** [comment]
I will add:

- Dead-code elimination: HLSL allows invalid stuff to happen in dead code. Glslang already eliminates functions not in the entry-point's call tree due to this, but further DCE is needed to catch all cases.  Example: `if (false) SSBO = A; else SSBO = B;` must resolve statically, not dynamically, to knowing SSBO is either A or B when SSBO is a StorageBuffer buffer object.

Also, the copy propagation must work through store/load to memory.  I'll update the top.

**Comment by dneto0** [comment]
Meta-point:  We should define the rules for this generalized SPIR-V dialect, and give it a name.   E.g. SPV_EXT_hlsl_relaxation1.     Then we can require `OpExtension "SPV_EXT_hlsl_relaxation"` in the module and validate it.  Also, when the last relaxation is eliminated, we can eliminate the OpExtension instruction for it.

**Comment by johnkslang** [comment]
We can know that extension after we formalize HLSL, as that is largely what it's definition will be. :)  Will be tough, because MS threw optimizations at it to fix it, which are hard to back-formalize to an input language.  Consider loop unwinding rules being part of the semantics of the language.  Lots has to be said about induction variables, fixed bounds (after copy propagation and constant folding, etc.). If it's not stated correctly, it will still be the reality of the situation that wins.

Alternatively, this is a largely circular definition WRT the passes:  Once we find the set of passes that eliminate the bad code, the specification of the input code is by definition code such that that set of passes fixes it.

Literally, HLSL is defined to be valid if a particular set of optimizations fixes it to a shader model.  I don't mind labeling such isomorphic SPIR-V with SPV_EXT_hlsl_relaxation, but suspect the best form the spec. will take is to say this same thing: It is SPIR-V such that after this set of transforms is done, yields valid SPIR-V.

Another way of labeling is with **OpModuleProcessed**. If **OpModuleProcessed** declares something like `"Preoptimized HLSL -> SPIR-V"`, then we know the starting state.  Each pass should add its own label, `"DCE xyz"`, `"GVN"`, whatever. Then one can see the history of that SPIR-V, see if something is missing, etc.

No strong claims here, just thinking through it a bit.

**Comment by greg-lunarg** [comment]
> Example: if (false) SSBO = A; else SSBO = B; must resolve statically, not dynamically, to knowing SSBO is either A or B when SSBO is a StorageBuffer buffer object.

Do we also need to handle: if (1.0 < 0.0) SSBO = A; else SSBO = B; ? If so, we will need to add constant folding to the top list. This feature is already captured in #664, #731, #709, but it would bump up the priority if this issue required it.

**Comment by greg-lunarg** [comment]
Should we also add inlining here?

The proposal would be to create a minimal inliner that only inlines functions that have opaque arguments or return values.

**Comment by dneto0** [comment]
> Should we also add inlining here?

I think yes.  Thanks for raising this.  I'll update the description.

**Comment by s-perron** [comment]
I think everything in this issue is done.  We will continue to deal with missing cases as they come up.
